# Generated by Django 4.2.9 on 2026-01-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER_PATIENT', 'Register Patient'), ('APPROVE_PATIENT', 'Approve Patient'), ('REJECT_PATIENT', 'Reject Patient'), ('UPLOAD_RECORD', 'Upload Medical Record'), ('VIEW_RECORDS', 'View Medical Records'), ('DOWNLOAD_RECORD', 'Download Medical Record'), ('VERIFY_RECORD', 'Verify Record on Blockchain')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='blockchain__user_id_8bf97d_idx'), models.Index(fields=['action'], name='blockchain__action_4b4103_idx'), models.Index(fields=['created_at'], name='blockchain__created_2da93d_idx')],
            },
        ),
    ]
