# Generated by Django 4.2.9 on 2026-01-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
