# Generated by Django 4.2.9 on 2026-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_medicalrecord_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether sensitive fields are encrypted in DB'),
        ),
    ]
