# Generated by Django 4.2.9 on 2026-01-26 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_department_doctornurseassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AlterModelOptions(
            name='doctornurseassignment',
            options={'verbose_name': 'Doctor-Nurse Assignment'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='users_appoi_appoint_0eb8dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='users_appoi_patient_05b0e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='users_notif_recipie_2469dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='users_notif_notific_af6ddd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_account_053b62_idx',
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='queue_number',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='scheduleexception',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='temporary_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('FOLLOW_UP', 'Follow-up Visit'), ('EMERGENCY', 'Emergency'), ('PROCEDURE', 'Medical Procedure'), ('VACCINATION', 'Vaccination')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctornurseassignment',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_APPOINTMENT', 'New Appointment Scheduled'), ('PATIENT_CHECK_IN', 'Patient Arrived / Checked In'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('RECORD_UPLOADED', 'New Medical Record Uploaded'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appointment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='exception_type',
            field=models.CharField(choices=[('OFF_DUTY', 'Off Duty / Leave'), ('EXTRA_SHIFT', 'Extra Shift')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='users_appoi_appoint_7f943d_idx'),
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='max_patients_per_slot',
        ),
    ]
