# Generated by Django 4.2.9 on 2026-02-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
