# Generated by Django 4.2.9 on 2026-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_mfa_enabled_user_otp_base32'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_preferred_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10),
        ),
    ]
