# Generated by Django 4.2.9 on 2026-02-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_mfa_preferred_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_preferred_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_base32',
        ),
    ]
