# Generated by Django 4.2.9 on 2026-02-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_number',
            field=models.CharField(blank=True, help_text='ID Number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_type',
            field=models.CharField(blank=True, help_text='Type of Valid Government ID', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='Filipino', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
