# Generated by Django 4.2.9 on 2026-02-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
