# Generated by Django 4.2.9 on 2026-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='government_id_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether sensitive PII fields are encrypted in DB'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
